/* tslint:disable */
 
/**
 * API Documentation
 * API - IT Asset Tracker
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleResponseDto
 */
export interface RoleResponseDto {
    /**
     * 
     * @type {number}
     * @memberof RoleResponseDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof RoleResponseDto
     */
    'roleCode': string;
    /**
     * 
     * @type {string}
     * @memberof RoleResponseDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof RoleResponseDto
     */
    'description': string;
}

